=======
AppStatus2=Under Review
GSTIN=GSTIN_22ABCDE1234F1Z2.jpg
bill_fname=raman
AppStatus=Under Review
submissiondate=Feb 28, 2025, 6:00 PM
Aadhar=Aadhaar_445588776688.jpeg
License=Licence.jpeg
admin_altphone=9685578946
NS2=office2
NS1=Office1
TechAadhar=1234 5678 7012
admin_email=hoya@gmail.com
Renewal=Feb 28, 2030, 6:00 PM
tech_altphone=9685578947
TechPan=ASDEE4455P
nameuser=venkat g
Board=Board.jpg
ID=Organisation_ID.jpg
Status=Payment Approved
lastRun=1740751333347
RGUsername=bharat@ikcontech.com
DomRenewalDate=Feb 18, 2030, 2:56 PM
admin_fname=prasad
OPANnum=ASDEE4455Q
gomain=teslao
AppTenure=5
Domain=victor
Orgname=victor
bill_altphone=9685578948
RGPPAss=Test@123
OGSTnum=22ABCDE0000A1J5
ex912=super
ex2l=super
admin_phone=9685578942
bill_email=tooya@gmail.com
Appno=IDR544528
BillAadhar=1234 5678 5012
Olicence=L12345MH2023PLC000001
admin_desig=Manager
AppNSRecordStatus=OnHold
tech_fname=srivas
BillPan=ASDEE4455P
AppSubmissionDate=Feb 18, 2025, 2:56 PM
tech_phone=9685578943
bill_desig=Accounts
ex5=super
IP2=1.10.80.22
>>>>>>>=branch 'devbranch' of https://github.com/IKCONDev/DNS-Automation.git
IP1=1.10.70.12
bill_phone=9685578954
tech_email=poya@gmail.com
Username=venkat.g@igbc.com
examp=super
tech_desig=Assig Mng
AdminPan=ASDEE4455L
exampl=super
AdminAadhar=1234 5678 8012
PAN=PAN_DXZOO7654R.jpeg
Appnumber=IDR528999
<<<<<<<=HEAD
