=======
AppStatus2=Under Review
bill_fname=raman
GSTIN=GSTIN_22ABCDE1234F1Z2.jpg
AppStatus=Under Review
submissiondate=Mar 4, 2025, 4:45 PM
Aadhar=Aadhaar_445588776688.jpeg
License=Licence.jpeg
RegistrarModifiedDate&Time=Feb 28, 2025, 4:08 PM
admin_altphone=9685578946
OrgName=swandhana
NS2=office2
TechAadhar=1234 5678 7012
NS1=Office1
admin_email=hoya@swandhana.com
Renewal=Mar 4, 2030, 4:45 PM
tech_altphone=9685578947
TechPan=ASDEE4455P
nameuser=venkat p
Board=Board.jpg
Licence-Documents=- 01.jpg=Organisation_ID.jpg
RDRDepartment=Banking
ID=Organisation_ID.jpg
RegistrarCreatedDate&Time=NA
Status=Payment Not Done
<<<<<<< HEAD
lastRun=1741092154095
DomainName=local.bank.in
=======
lastRun=1741095725332
DomainName=swandhana.bank.in
>>>>>>> branch 'devbranch' of https://github.com/IKCONDev/DNS-Automation.git
Adahhar-Documents=- 04.jpg=Aadhaar_445588776688.jpeg
AOAdharDocComment=Approved
RGUsername=bharat@ikcontech.com
Domstatus=Inactive
admin_fname=prasad
DomRenewalDate=Mar 4, 2030, 4:45 PM
1=676
OPANnum=ASDEE4455Q
2=677
3=678
gomain=teslao
AppTenure=5
<<<<<<< HEAD
Domain=local
Orgname=local
bill_altphone=9685578948
=======
Orgname=swandhana
Domain=swandhana
>>>>>>> branch 'devbranch' of https://github.com/IKCONDev/DNS-Automation.git
RGPPAss=Test@123
bill_altphone=9685578948
InAmount=5900
OGSTnum=22ABCDE0000A1J5
ex912=super
ex2l=super
admin_phone=9685578942
RDRUserRole=IDRBTADMIN
bill_email=tooya@swandhana.com
Appno=IDR159924
BillAadhar=1234 5678 5012
Olicence=L12345MH2023PLC000001
admin_desig=Manager
RegistrarDepCreatedDate&Time=NA
AppNSRecordStatus=OnHold
RDRUserName=Bharat Kumar
Pan-Documents=- 05.jpg=PAN_DXZOO7654R.jpeg
tech_fname=srivas
UserID1=hoya@swandhana.com
BillPan=ASDEE4455P
InvoiceDate=Mar 4, 2025, 2:32 PM
AppSubmissionDate=Mar 4, 2025, 4:45 PM
UserID4=venkat.p@swandhana.com
tech_phone=9685578943
UserID3=tooya@swandhana.com
UserID2=hoya@swandhana.com
DRStatus=Active
bill_desig=Accounts
ex5=super
UserName4=venkat p
RegistrarModified=Bharat Kumar
Role4=Super Admin
<<<<<<< HEAD
IP2=1.10.82.57
UserName2=prasad
=======
UserName2=prasad
IP2=193.0.12.21
>>>>>>> branch 'devbranch' of https://github.com/IKCONDev/DNS-Automation.git
Role3=Billing Officer
>>>>>>>=branch 'devbranch' of https://github.com/IKCONDev/DNS-Automation.git
UserName3=raman
Role2=Administrative Officer
<<<<<<< HEAD
IP1=1.10.71.12
=======
IP1=193.0.21.12
>>>>>>>=branch 'devbranch' of https://github.com/IKCONDev/DNS-Automation.git
>>>>>>> branch 'devbranch' of https://github.com/IKCONDev/DNS-Automation.git
Role1=Administrative Officer
UserName1=prasad
bill_phone=9685578954
RegistrarDepModifiedDate&Time=NA
tech_email=poya@swandhana.com
AOAdharDocStatus=Organisation_ID.jpg
Username=venkat.p@swandhana.com
examp=super
tech_desig=Assig Mng
AdminPan=ASDEE4455L
exampl=super
AdminAadhar=1234 5678 8012
PAN=PAN_DXZOO7654R.jpeg
Appnumber=IDR159924
<<<<<<<=HEAD
