bill_fname=raman
GSTIN=GSTIN_22ABCDE1234F1Z2.jpg
submissiondate=Feb 20, 2025, 5:11 PM
Aadhar=Aadhaar_445588776688.jpeg
License=Licence.jpeg
admin_altphone=9685578946
NS2=office2
TechAadhar=1234 5678 7012
NS1=Office1
admin_email=hoya@gmail.com
Renewal=Feb 20, 2030, 5:11 PM
tech_altphone=9685578947
TechPan=ASDEE4455P
nameuser=sravan p
Board=Board.jpg
ID=Organisation_ID.jpg
lastRun=1740573216399
RGUsername=bharat@ikcontech.com
admin_fname=prasad
OPANnum=ASDEE4455Q
gomain=teslao
Domain=hgfc
Orgname=hgfc
bill_altphone=9685578948
RGPPAss=Test@123
OGSTnum=22ABCDE0000A1J5
ex912=super
ex2l=super
admin_phone=9685578942
bill_email=tooya@gmail.com
Appno=IDR789495
BillAadhar=1234 5678 5012
Olicence=L12345MH2023PLC000001
admin_desig=Manager
tech_fname=srivas
BillPan=ASDEE4455P
tech_phone=9685578943
bill_desig=Accounts
ex5=super
IP2=1.10.10.20
IP1=1.10.10.10
bill_phone=9685578954
DomRenewalDate=Feb 18, 2030, 2:56 PM
tech_email=poya@gmail.com
Username=sravan.p@ikcontech.com
examp=super
tech_desig=Assig Mng
AdminPan=ASDEE4455L
exampl=super
AdminAadhar=1234 5678 8012
PAN=PAN_DXZOO7654R.jpeg
