
baseURL=http://10.10.1.138:4200/#/login
RbaseURL=http://10.10.1.138:4200/#/rgtr-login
Aadhar=C:\\Users\\VenkateshUdaru\\eclipse2\\DNSproject\\src\\test\\resources\\Documents\\Aadhaar_445588776688.jpeg
GSTIN=C:\\Users\\VenkateshUdaru\\eclipse2\\DNSproject\\src\\test\\resources\\Documents\\GSTIN_22ABCDE1234F1Z2.jpg
License=C:\\Users\\VenkateshUdaru\\eclipse2\\DNSproject\\src\\test\\resources\\Documents\\Licence.jpeg
PAN=C:\\Users\\VenkateshUdaru\\eclipse2\\DNSproject\\src\\test\\resources\\Documents\\PAN_DXZOO7654R.jpeg
ID=C:\\Users\\VenkateshUdaru\\eclipse2\\DNSproject\\src\\test\\resources\\Documents\\Organisation_ID.jpg
Board=C:\\Users\\VenkateshUdaru\\eclipse2\\DNSproject\\src\\test\\resources\\Documents\\Board.jpg


OGSTnum=22ABCDE0000A1J5
bill_fname=raman
submissiondate=Feb 15, 2025, 7:28 AM
admin_phone=9685578942
admin_altphone=9685578946
bill_email=billing@gmail.com
Appno=IDR683364
NS2=office2
BillAadhar=1234 5678 5012
TechAadhar=1234 5678 7012
NS1=Office1
admin_email=admin@gmail.com
Renewal=Feb 15, 2030, 7:28 AM
tech_altphone=9685578947
TechPan=ASDEE4455P
admin_desig=Manager
tech_fname=srivas
BillPan=ASDEE4455P
tech_phone=9685578943
bill_desig=Accounts
IP2=1.10.10.20
IP1=1.10.10.10
admin_fname=prasad
bill_phone=9685578954
tech_email=technical@gmail.com
Username=venkatesh.u@ikcontech.com
tech_desig=Assig Mng
Domain=simon
Orgname=mexican
bill_altphone=9685578948