# Environment Settings
baseURL=http://10.10.1.138:4200/#/login
RbaseURL=http://10.10.1.138:4200/#/rgtr-login
Domain=
OrgName=Ikcontech solutions
BOOrgname=Ikcontech solutions
TOOrgname=Ikcontech solutions
ADocumentType=Aadhaar
PDocumentType=PAN
OrgDocumentType=Organisation Id

UserId=bharat@ikcontech.com
UserID=prakash@ikcontech.com
RoleName=IDRBTADMIN
DepartmentName=IT

AOPersonname=virat
AODesignation=Admin1
AOMobileNumber=2342343343
AOEmailId=virat@ikcontechcom
AORole=Administrative Officer	
AOLoginStatus=Approved
AOIsActive=true