# Environment Settings
<<<<<<< HEAD
baseURL=https://10.10.1.138/#/login
RbaseURL=https://registrar.idrbt.ac.in/#/rgtr-login
=======
baseURL=https://10.10.1.138:/#/login
RbaseURL=https://10.10.1.138/#/rgtr-login
>>>>>>> branch 'devbranch' of https://github.com/IKCONDev/DNS-Automation.git

//Dashboard 
APPorgname=Information
APPDomainName=rain.bank.in
AppQRegistrationDate=Feb 17, 2025, 2:56 PM
AppQRenewalDate=Feb 17, 2030, 2:56 PM
AppQStatus=Under Review

Appno=IDR132869




//Application 

AppSubmissionDate=Feb 18, 2025, 2:56 PM
AppStatus=Under Review
AppPaymentStatus=Payment Not Done
AppNSRecordStatus=OnHold
AppTenure=5
AppStatus2=Under Review

//DOMAIN


DomRenewalDate=Feb 18, 2030, 2:56 PM	
Domstatus=Inactive

//INVOICE
DomainName=canara.bank.in

InAmount=5900
Invoicedownload=Invoice
InvoiceDate=Feb 22, 2025, 10:46 PM
Status=Payment Approved


//DRUserManagement
RDRUserName=Bharat Kumar
RDRDepartment=Banking
RDRUserRole=IDRBTADMIN
DRStatus=Active



//RegistrarRoles
RegistrarCreatedDate&Time=NA
RegistrarModified=NA
RegistrarModifiedDate&Time=NA

//RegistrarDepartment
RegistrarDepCreatedDate&Time=NA
RegistrarDepModifiedDate&Time=NA

OrgName=Canara Bank

ADocumentType=Aadhaar
PDocumentType=PAN
OrgDocumentType=Organisation Id

UserId=bharat@ikcontech.com
UserID=prabhakaran.a@ikcontech.com
RoleName=IDRBTADMIN
DepartmentName=Banking

//RegistrantUserManagement

UserID1=canarabill@gmail.com
UserID2=canaratech@gmail.com
UserID3=prabhakaran.a@ikcontech.com
UserID4=vaishnav@gmail.com

UserName1=bose
UserName2=canaratech
UserName3=Prabhakaran
UserName4=vaishnav

Role1=Billing Officer
Role2=Technical Officer
Role3=Super Admin
Role4=Administrative Officer

AOPersonname=Vinod
AODesignation=Admin
AOMobileNumber=9026332456
AOEmailId=vinod.kethu@ikcontech.com
AORole=Administrative Officer	
AOLoginStatus=Approved
AOIsActive=true

BOPersonname=Prabhakaran
BODesignation=Billing
BOMobileNumber=8907439358
BOEmailId=prabhakaran.a@ikcontech.com
BORole=Billing Officer
BOLoginStatus=Approved
BOIsActive=true


TOPersonname=Prakash
TODesignation=Technical
TOMobileNumber=6789642435
TOEmailId=bhargavi.prakash@ikcontech.com
TORole=Technical Officer
TOLoginStatus=Approved
TOIsActive=true


AOAdharDocStatus=Approved
AOAdharDocComment=NA

Aadhar=C:\\Users\\VenkateshUdaru\\OneDrive - IKCON TECHNOLOGIES INC\\Desktop\\Automation\\DNSproject(new)\\DNSproject\\src\\test\\resources\\Documents\\Aadhaar_445588776688.jpeg
GSTIN=C:\\Users\\VenkateshUdaru\\OneDrive - IKCON TECHNOLOGIES INC\\Desktop\\Automation\\DNSproject(new)\\DNSproject\\src\\test\\resources\\Documents\\GSTIN_22ABCDE1234F1Z2.jpg
License=C:\\Users\\VenkateshUdaru\\OneDrive - IKCON TECHNOLOGIES INC\\Desktop\\Automation\\DNSproject(new)\\DNSproject\\src\\test\\resources\\Documents\\Licence.jpeg
PAN=C:\\Users\\VenkateshUdaru\\OneDrive - IKCON TECHNOLOGIES INC\\Desktop\\Automation\\DNSproject(new)\\DNSproject\\src\\test\\resources\\Documents\\PAN_DXZOO7654R.jpeg
ID=C:\\Users\\VenkateshUdaru\\OneDrive - IKCON TECHNOLOGIES INC\\Desktop\\Automation\\DNSproject(new)\\DNSproject\\src\\test\\resources\\Documents\\Organisation_ID.jpg
Board=C:\\Users\\VenkateshUdaru\\OneDrive - IKCON TECHNOLOGIES INC\\Desktop\\Automation\\DNSproject(new)\\DNSproject\\src\\test\\resources\\Documents\\Board.jpg




